name: Root.io Remediation

on:
  push:
    branches: [ main ]

jobs:
  remediate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p remediation-output

      - name: Run Root.io Remediation (Direct)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/remediation-output:/output \
            public.ecr.aws/rootio/remediation-client:latest \
            ${{ vars.ROOTIO_ORG_ID }} \
            ${{ secrets.ROOTIO_API_TOKEN }} \
            ${{ vars.ROOTIO_REGISTRY_CREDENTIALS_ID }} \
            zoheb3454/keycloak:26.3.3-debian-12-r0 \
            amd64 \
            /output
