name: Root.io Remediation

on:
  push:
    branches: [ main ]

jobs:
  remediate:
    runs-on: ubuntu-latest
    environment: Root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Root.io Remediation
        uses: zohebk8s/rootio-remediation-action@main
        with:
          ORG_ID: ${{ vars.ROOTIO_ORG_ID }}
          ROOT_API_TOKEN: ${{ secrets.ROOTIO_API_TOKEN }}
          CREDS_ID: ${{ vars.ROOTIO_REGISTRY_CREDENTIALS_ID }}
          IMAGE_REPO_TAG: zoheb3454/keycloak:26.3.3-debian-12-r0
