name: Root.io Remediation

on:
  push:
    branches: [ main ]

jobs:
  remediate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Root.io Remediation
        uses: rootio-avr/rootio-remediation-action@latest
        with:
          org_id: ${{ env.ROOTIO_ORG_ID }}
          api_token: ${{ secrets.ROOTIO_API_TOKEN }}
          registry_credentials_id: ${{ env.ROOTIO_REGISTRY_CREDENTIALS_ID }}
          image_reference: zoheb3454/keycloak:26.3.3-debian-12-r0
